### ISSUE TITLE
Update Vite and Svelte-kit

### ISSUE THREAD

**Issue by AlexisPister** [duckdb-wasm-examples/sveltekit-typescript#7]
I have an application with Sveltekit 2.8.5 and Vite 5.4.11 where I load a Duckdb instance the same way than in this repo. It works for development but when running `vite build` I get the following error: 

```
node:internal/event_target:1101
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: Cannot destructure property 'mod' of '_.workerData' as it is undefined.
    at We (/Users/apister/Documents/Projects/ECCI/node_modules/@duckdb/duckdb-wasm/dist/duckdb-node.cjs:1:2022)
    at /Users/apister/Documents/Projects/ECCI/node_modules/@duckdb/duckdb-wasm/dist/duckdb-node.cjs:1:1361
    at /Users/apister/Documents/Projects/ECCI/node_modules/@duckdb/duckdb-wasm/dist/duckdb-node.cjs:1:222
    at Object.<anonymous> (/Users/apister/Documents/Projects/ECCI/node_modules/@duckdb/duckdb-wasm/dist/duckdb-node.cjs:1:32192)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1698:10)
    at Module.load (node:internal/modules/cjs/loader:1303:32)
    at Function._load (node:internal/modules/cjs/loader:1117:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)

Node.js v23.3.0
```

Would it be possible to get a sveltekit-vite-typescript-duckdb template example with up to date packages? Thanks!

**Comment by nx10** [comment]
Got it to work by dynamically importing during runtime. Seems to work both in dev mode and static builds

```typescript
import duckdb_wasm from '@duckdb/duckdb-wasm/dist/duckdb-mvp.wasm?url';
import mvp_worker from '@duckdb/duckdb-wasm/dist/duckdb-browser-mvp.worker.js?url';
import duckdb_wasm_eh from '@duckdb/duckdb-wasm/dist/duckdb-eh.wasm?url';
import eh_worker from '@duckdb/duckdb-wasm/dist/duckdb-browser-eh.worker.js?url';
import type { AsyncDuckDB, DuckDBBundles } from '@duckdb/duckdb-wasm';
import { browser } from '$app/environment';

// Call this in onMount(...)
export async function instantiateDuckDb(): Promise<AsyncDuckDB> {

  if (!browser) {
    Error("Can only instantiate DuckDB from browser.")
  }

  const duckdb = await import('@duckdb/duckdb-wasm');

  const MANUAL_BUNDLES: DuckDBBundles = {
    mvp: {
      mainModule: duckdb_wasm,
      mainWorker: mvp_worker,
    },
    eh: {
      mainModule: duckdb_wasm_eh,
      mainWorker: eh_worker,
    },
  };
  // Select a bundle based on browser checks
  const bundle = await duckdb.selectBundle(MANUAL_BUNDLES);
  // Instantiate the asynchronus version of DuckDB-wasm
  const worker = new Worker(bundle.mainWorker!);
  const logger = new duckdb.ConsoleLogger();
  const db = new duckdb.AsyncDuckDB(logger, worker);
  await db.instantiate(bundle.mainModule, bundle.pthreadWorker);
  return db;
}
```

**Comment by bmschmidt** [comment]
Thanks! Going to take a stab at upgrading here.

**Comment by nx10** [comment]
Awesome!

**Comment by bmschmidt** [comment]
done!

Would be nice if it ran on ssr endpoints too, will open a separate ticket for that.
